<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS84xdte\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS84xdte/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerS84xdte.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerS84xdte\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerS84xdte\appProdProjectContainer([
    'container.build_hash' => 'S84xdte',
    'container.build_id' => 'a05d4745',
    'container.build_time' => 1687491612,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS84xdte');
