<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4iblxgr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4iblxgr/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4iblxgr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4iblxgr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4iblxgr\appProdProjectContainer([
    'container.build_hash' => '4iblxgr',
    'container.build_id' => 'b20d1ea4',
    'container.build_time' => 1686822267,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4iblxgr');
