/**
* 2007-2023 PrestaShop
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@prestashop.com so we can send you a copy immediately.
*
* DISCLAIMER
*
* Do not edit or add to this file if you wish to upgrade PrestaShop to newer
* versions in the future. If you wish to customize PrestaShop for your
* needs please refer to http://www.prestashop.com for more information.
*
*  @author    PrestaShop SA <contact@prestashop.com>
*  @copyright 2007-2023 PrestaShop SA
*  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*
* Don't forget to prefix your containers with your own identifier
* to avoid any conflicts with others containers.
*/

var ChatGptForm = (function () {
    function ChatGptForm(options) {
        var settings = Object.assign({}, {
        }, options);
    }

    ChatGptForm.renderToolTip = function (content) {
        return '<span class="help-box gpt-tooltip" data-toggle="popover" data-trigger="hover" data-html="true" data-content="' + content + '" data-original-title="" title=""></span>';
    }

    ChatGptForm.descriptionForm = function () {
        var output =
        '<div class="tabs js-tabs">' +
            '<ul class="nav nav-tabs js-nav-tabs" id="form-nav" role="tablist">' +
                '<li id="tab_step1" class="nav-item"><a href="#gptgeneral" role="tab" data-toggle="tab" class="font-weight-bold nav-link active" aria-selected="true">General</a></li>' +
                '<li id="tab_step2" class="nav-item" ' + ((adminPageName != 'productsList' && adminPageName != 'productForm') ? 'style="display: none"' : '') + '><a href="#gptadvanced" role="tab" data-toggle="tab" class="font-weight-bold nav-link" aria-selected="true">Advanced</a></li>' +
            '</ul>' +
        '</div>' +
        '<div class="tab-content" style="border: 1px solid #25b9d7;">' +
            '<div class="form-contenttab tab-pane active" role="tabpanel" id="gptgeneral">' +
                (adminPageName != 'productForm' && adminPageName != 'categoryForm' && adminPageName != 'cmsForm'
                    ?   '<div class="row form-inline mb-3">' +
                            '<label class="control-label col-md-6 justify-content-end text-right">' + (adminPageName == 'categoriesList' ? gptI18n.bulkGeneratingSkipExistingCategoryDescription : gptI18n.bulkGeneratingSkipExistingDescription) + ':</label>' +
                            '<div class="col-md-3">' +
                                '<div class="input-group">' +
                                    '<span class="ps-switch">' +
                                        '<input id="skip_existing_content_0" class="ps-switch" name="check_empty_content" value="0" ' + (gptPageSettings[adminPageName].skipExistingDescription ? '' : 'checked="checked"') + ' type="radio" aria-label="No" onchange="document.getElementById(\'replacecontentswicher\').style.display=($(this).is(\':checked\') ? \'block\' : \'none\');">' +
                                        '<label for="skip_existing_content_0">' + gptI18n.no + '</label>' +
                                        '<input id="skip_existing_content_1" class="ps-switch" name="check_empty_content" value="1" ' + (gptPageSettings[adminPageName].skipExistingDescription ? 'checked="checked"' : '') + ' type="radio" aria-label="Yes" onchange="document.getElementById(\'replacecontentswicher\').style.display=($(this).is(\':checked\') ? \'none\' : \'block\');">' +
                                        '<label for="skip_existing_content_1">' + gptI18n.yes + '</label>' +
                                        '<span class="slide-button"></span>' +
                                    '</span>' +
                                '</div>' +
                            '</div>' +
                        '</div>'
                    : ''
                ) +

                '<div id="replacecontentswicher" style="' + (gptPageSettings[adminPageName].skipExistingDescription ? 'display: none;' : '') + '">' +
                    '<div class="row form-inline mb-3">' +
                        '<label class="control-label col-md-6 justify-content-end text-right">' + ChatGptForm.renderToolTip('<b>Add</b> - the new content generated by ChatGPT will be added after your current description.<br/><b>Replace</b> - your current description will be replaced with the new one generated by ChatGPT') + ' ' + (adminPageName == 'cmsForm' ? gptI18n.bulkConfirmGenerateContent : gptI18n.bulkConfirmGenerateDescription) + ':</label>' +
                        '<div class="col-md-3">' +
                            '<div class="input-group">' +
                                '<span class="ps-switch">' +
                                    '<input id="allow_gen_content_0" class="ps-switch" name="allow_gen_content" value="1" ' + (gptPageSettings[adminPageName].replaceContent ? 'checked="checked"' : '') + ' type="radio" aria-label="No">' +
                                    '<label for="allow_gen_content_0">Replace</label>' +
                                    '<input id="allow_gen_content_1" class="ps-switch" name="allow_gen_content" value="0" ' + (gptPageSettings[adminPageName].replaceContent ? '' : 'checked="checked"') + ' type="radio" aria-label="Yes">' +
                                    '<label for="allow_gen_content_1">Add</label>' +
                                    '<span class="slide-button"></span>' +
                                '</span>' +
                            '</div>' +
                        '</div>' +
                    '</div>' +
                '</div>' +
                '<div class="row form-inline mb-3">' +
                    '<label class="control-label col-md-6 justify-content-end text-right">' + gptI18n.maxNumberWords + ':</label>' +
                    '<div class="col-md-6">' +
                        '<div class="input-group">' +
                            '<input type="number" id="gpt_description_length" class="form-control" min="' + gptPageSettings[adminPageName].minWords + '" step="' + gptPageSettings[adminPageName].step + '" max="' + gptPageSettings[adminPageName].maxWords + '" value="' + gptPageSettings[adminPageName].words + '">' +
                            '<div class="input-group-append">' +
                                '<span class="input-group-text"> ' + gptI18n.words + '</span>' +
                            '</div>' +
                        '</div>' +
                    '</div>' +
                '</div>' +

                '<div style="' + (gptLanguages.length <= 1 ? 'display: none;' : '') + '">' +
                    ChatGptContent.getLanguageChooserHtml(gptLanguages) +
                '</div>' +

            '</div>' +
            '<div class="form-contenttab tab-pane" role="tabpanel" id="gptadvanced" ' + ((adminPageName != 'productsList' && adminPageName != 'productForm') ? 'style="display: none"' : '') + '>' +

                

                '<div class="row form-inline mb-3">' +
                    '<label class="control-label col-md-7 justify-content-end text-right">' + ChatGptForm.renderToolTip('Improve results of ChatGPT content generation by using the <b>category</b> value of the product') + ' ' + gptI18n.useProductCategory + ':</label>' +
                    '<div class="col-md-3">' +
                        '<div class="input-group">' +
                            '<span class="ps-switch">' +
                                '<input id="use_product_category_0" class="ps-switch" name="use_product_category" value="0" type="radio" aria-label="No">' +
                                '<label for="use_product_category_0">' + gptI18n.no + '</label>' +
                                '<input id="use_product_category_1" class="ps-switch" name="use_product_category" value="1" checked="checked" type="radio" aria-label="Yes">' +
                                '<label for="use_product_category_1">' + gptI18n.yes + '</label>' +
                                '<span class="slide-button"></span>' +
                            '</span>' +
                        '</div>' +
                    '</div>' +
                '</div>' +

                '<div class="row form-inline mb-3">' +
                    '<label class="control-label col-md-7 justify-content-end text-right">' + ChatGptForm.renderToolTip('Improve results of ChatGPT content generation by using the <b>brand</b> value of the product') + ' ' + gptI18n.useProductBrand + ':</label>' +
                    '<div class="col-md-3">' +
                        '<div class="input-group">' +
                            '<span class="ps-switch">' +
                                '<input id="use_product_brand_0" class="ps-switch" name="use_product_brand" value="0" type="radio" aria-label="No">' +
                                '<label for="use_product_brand_0">' + gptI18n.no + '</label>' +
                                '<input id="use_product_brand_1" class="ps-switch" name="use_product_brand" value="1" checked="checked" type="radio" aria-label="Yes">' +
                                '<label for="use_product_brand_1">' + gptI18n.yes + '</label>' +
                                '<span class="slide-button"></span>' +
                            '</span>' +
                        '</div>' +
                    '</div>' +
                '</div>' +

                '<div class="row form-inline mb-3">' +
                    '<label class="control-label col-md-7 justify-content-end text-right">' + ChatGptForm.renderToolTip('Improve results of ChatGPT content generation by using the <b>EAN</b> value of the product') + ' ' + gptI18n.useProductEan + ':</label>' +
                    '<div class="col-md-3">' +
                        '<div class="input-group">' +
                            '<span class="ps-switch">' +
                                '<input id="use_product_ean_0" class="ps-switch" name="use_product_ean" value="0" type="radio" aria-label="No">' +
                                '<label for="use_product_ean_0">' + gptI18n.no + '</label>' +
                                '<input id="use_product_ean_1" class="ps-switch" name="use_product_ean" value="1" checked="checked" type="radio" aria-label="Yes">' +
                                '<label for="use_product_ean_1">' + gptI18n.yes + '</label>' +
                                '<span class="slide-button"></span>' +
                            '</span>' +
                        '</div>' +
                    '</div>' +
                '</div>' +

                '<div class="row form-inline mb-3">' +
                    '<label class="control-label col-md-7 justify-content-end text-right">' + ChatGptForm.renderToolTip('<b>Description</b> - you will get a common description of the product.<br/><b>Characteristics</b> - you will the list of product features') + ' ' + gptI18n.descriptionOrCharacteristics + ':</label>' +
                    '<div class="col-md-3">' +
                        '<div class="input-group">' +
                            '<span class="ps-switch">' +
                                '<input id="desc_or_characteristics_0" class="ps-switch" name="desc_or_characteristics" value="characteristics" type="radio" aria-label="No">' +
                                '<label for="desc_or_characteristics_0">Charact</label>' +
                                '<input id="desc_or_characteristics_1" class="ps-switch" name="desc_or_characteristics" value="description" checked="checked" type="radio" aria-label="Yes">' +
                                '<label for="desc_or_characteristics_1">Descr</label>' +
                                '<span class="slide-button"></span>' +
                            '</span>' +
                        '</div>' +
                    '</div>' +
                '</div>' +

            '</div>' +
        '</div>';

        return output;
    };

    ChatGptForm.traslationForm = function () {
        var output =
        '<div class="mb-2" style="' + (gptLanguages.length <= 1 ? 'display: none;' : '') + '">' +
            ChatGptForm.getOneToManyLanguagesSelectorHtml(gptLanguages) +
        '</div>' +
        (adminPageName != 'productForm' && adminPageName != 'categoryForm' && adminPageName != 'cmsForm'
            ? '<div class="row form-inline mt-4">' +
                '<label class="control-label col-md-6 justify-content-end text-right">' + (adminPageName == 'categoriesList' ? gptI18n.bulkGeneratingSkipExistingCategoryDescription : gptI18n.bulkGeneratingSkipExistingDescription) + ':</label>' +
                '<div class="col-md-3">' +
                    '<div class="input-group">' +
                        '<span class="ps-switch">' +
                            '<input id="skip_existing_content_0" class="ps-switch" name="check_empty_content" value="0" ' + (gptPageSettings[adminPageName].skipExistingDescription ? '' : 'checked="checked"') + ' type="radio" aria-label="No">' +
                            '<label for="skip_existing_content_0">' + gptI18n.no + '</label>' +
                            '<input id="skip_existing_content_1" class="ps-switch" name="check_empty_content" value="1" ' + (gptPageSettings[adminPageName].skipExistingDescription ? 'checked="checked"' : '') + ' type="radio" aria-label="Yes">' +
                            '<label for="skip_existing_content_1">' + gptI18n.yes + '</label>' +
                            '<span class="slide-button"></span>' +
                        '</span>' +
                    '</div>' +
                '</div>' +
            '</div>'
            : ''
        );

        return output;
    }

    ChatGptForm.traslationTitleForm = function () {
        var output =
        '<div class="mb-2" style="' + (gptLanguages.length <= 1 ? 'display: none;' : '') + '">' +
            ChatGptForm.getOneToManyLanguagesSelectorHtml(gptLanguages) +
        '</div>' +
        (adminPageName != 'productForm' && adminPageName != 'categoryForm' && adminPageName != 'cmsForm'
            ? '<div class="row form-inline mt-4">' +
                '<label class="control-label col-md-6 justify-content-end text-right">' + (adminPageName == 'categoriesList' ? gptI18n.bulkGeneratingSkipExistingCategoryTitle : gptI18n.bulkGeneratingSkipExistingTitle) + ':</label>' +
                '<div class="col-md-3">' +
                    '<div class="input-group">' +
                        '<span class="ps-switch">' +
                            '<input id="skip_existing_content_0" class="ps-switch" name="check_empty_content" value="0" ' + (gptPageSettings[adminPageName].skipExistingTitle ? '' : 'checked="checked"') + ' type="radio" aria-label="No">' +
                            '<label for="skip_existing_content_0">' + gptI18n.no + '</label>' +
                            '<input id="skip_existing_content_1" class="ps-switch" name="check_empty_content" value="1" ' + (gptPageSettings[adminPageName].skipExistingTitle ? 'checked="checked"' : '') + ' type="radio" aria-label="Yes">' +
                            '<label for="skip_existing_content_1">' + gptI18n.yes + '</label>' +
                            '<span class="slide-button"></span>' +
                        '</span>' +
                    '</div>' +
                '</div>' +
            '</div>'
            : ''
        );

        return output;
    }

    ChatGptForm.traslationProcess = function () {
        var output =
            '<div>' +
                '<span>Translating in progress...</span>' +
                '<span id="process_translate_status" style="color: darkred;"></span>' +
                '<div class="progress mt-2" style="width: 100%">' +
                    '<div class="progress-bar progress-bar-striped" role="progressbar" style="width: 0%">' +
                        '<span>0 %</span>' +
                    '</div>' +
                '</div>' +
                '<div id="process_translate_error_log" class="alert alert-danger mt-2" style="display: none;"><p class="alert-text"></p></div>' +
                '<div id="process_translate_success_log" class="alert alert-success mt-2" style="display: none;"><p class="alert-text"></p></div>' +
            '</div>';

        return output;
    }

    /**
     * Get html of language chooser
     *
     * @return string
     */
    ChatGptForm.getOneToManyLanguagesSelectorHtml  = function(languages, idLangDefault) {
        if (typeof languages == 'undefined') {
            languages = gptLanguages;
        }

        if (typeof idLangDefault == 'undefined') {
            idLangDefault = (new ChatGptContent).getPageLanguageId();
        }

        var checkboxClass = 'checkbox-' + (new Date()).getTime();
        var radioClass = 'radio-' + (new Date()).getTime();
        var idLang = 0;
        var checkboxLanguagesList = '';
        for (var i = 0; i < languages.length; i++) {
            checkboxLanguagesList +=
                '<tr ' + (languages[i].id_lang == idLangDefault ? 'style="display: none;"' : '') + '>' +
                    '<td>' +
                        '<div class="checkbox">' +
                            '<div class="md-checkbox md-checkbox-inline"><label><input type="checkbox" class="gpt-languages-list ' + checkboxClass + '" name="" value="' + languages[i].id_lang + '" ' + (languages[i].id_lang == idLang ? 'checked="checked"' : '') +'><i class="md-checkbox-control"></i>' + languages[i].name + '</label></div>' +
                        '</div>' +
                    '</td>' +
                '</tr>';
        }
        var radioLanguagesList = '';
        for (var i = 0; i < languages.length; i++) {
            radioLanguagesList +=
                '<tr>' +
                    '<td>' +
                        '<div class="radio">' +
                            '<div class="m-0 form-check-radio"><label class="form-check-label"><input type="radio" class="' + radioClass + '" name="origin_language" value="' + languages[i].id_lang + '" ' + (languages[i].id_lang == idLangDefault ? 'checked="checked"' : '') +' onchange="var tmpLId=this.value; $(\'.' + checkboxClass + '\').each(function () {var w=$(this).closest(\'tr\'); if (this.value==tmpLId){ w.hide(); w.find(\'input\').prop(\'checked\', false); } else w.show();})"><i class="form-check-round"></i>' + languages[i].name + '</label></div>' +
                        '</div>' +
                    '</td>' +
                '</tr>';
        }

        return  '<div class="row type-choice">' +
                    '<label class="control-label col-md-6 justify-content-start">Translate from:</label>' +
                    '<label class="control-label col-md-6 justify-content-start">Translate to:</label>' +
                '</div>' +
                '<div class="row type-choice">' +
                        '<div class="col-md-6">' +
                            '<div class="choice-table pl-1px">' +
                                '<table class="table table-bordered mb-0">' +
                                    '<thead>' +
                                        '<tr>' +
                                            '<th class="checkbox">Select one</th>' +
                                        '</tr>' +
                                    '</thead>' +
                                    '<tbody>' +
                                        radioLanguagesList +
                                    '</tbody>' +
                                '</table>' +
                            '</div>' +
                        '</div>' +
                        '<div class="col-md-6">' +
                            '<div class="choice-table">' +
                                '<table class="table table-bordered mb-0">' +
                                    '<thead>' +
                                        '<tr>' +
                                            '<th class="checkbox">' +
                                                '<div class="md-checkbox"><label><input type="checkbox" class="js-choice-table-select-all" onchange="var p=$(this).prop(\'checked\'),tmpLId=$(\'input[name=\\\'origin_language\\\']:checked\').val(); $(\'.' + checkboxClass + '\').each(function () {if (this.value != tmpLId) $(this).prop(\'checked\', p);})"><i class="md-checkbox-control"></i> ' + gptI18n.selectAll + '</label></div>' +
                                            '</th>' +
                                        '</tr>' +
                                    '</thead>' +
                                    '<tbody>' +
                                        checkboxLanguagesList +
                                    '</tbody>' +
                                '</table>' +
                            '</div>' +
                        '</div>' +
                    '</div>';
    };

    return ChatGptForm;
})();
